### ISSUE TITLE
formalize dev data set and creation instructions

### ISSUE THREAD

**Issue by norton120** [Health-Union/snowshu#30]
## Why?

Right now we don’t have clear “getting set up to contribute” directions using the SNOWSHU\_DEVELOPMENT datasets. fix that! 

## Def Of Done:

we have: 

* csv files in a folder structure that makes db->schema->relation easy
* instructions for views
* instructions for users & roles
* detailed descriptions of which relations relate to which other relations and how \(when tables have intended outliers etc\)

‌

[Issue created by ethanknox: 2020-01-16]
[Last updated on bitbucket: 2020-01-17]

**Comment by ankur112358** [comment]
Developer docs were present [earlier](https://github.com/Health-Union/snowshu/commit/153d542585f1627633d0d6400ce5fbedf13edeb6) in the repo but was then removed. They can be used as a reference here.
