### ISSUE TITLE
Use SHOW DATABASE for initial DB lookup in Snowflake Adapter

### ISSUE THREAD

**Issue by BenjaminDavison** [Health-Union/snowshu#40]
Hi all,

When trying to run `snowshu analyze` we're running into this error:

`sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002003 (02000): 01938587-0027-5d4d-0000-012516bbcafe: SQL compilation error:
Database 'UTIL_DB' does not exist or not authorized.
[SQL:  SELECT DISTINCT database_name
FROM "UTIL_DB"."INFORMATION_SCHEMA"."DATABASES"
WHERE is_transient = 'NO'
AND database_name <> 'UTIL_DB'
]`

On our Snowflake installation, we don't have a `UTIL_DB`, but we do have a `SNOWFLAKE` database with the required tables.

Is UTIL_DB Something you've cloned from the Snowflake database?

Thanks,

Ben

**Comment by norton120** [comment]
Ah yeah, this is an oversight assuming admin permissions. `UTIL_DB` is core snowflake but requires accountadmin to query, which is probably the wrong way to tackle this. The right answer is probably to migrate the databases query in the Snowflake adapter to use `SHOW DATABASES`. We can hit this pretty quick and get a release patch out.

**Comment by norton120** [comment]
need to update [this statement](https://github.com/Health-Union/snowshu/blob/979d5eebe243d0f4819727cc6f82ed62e46bdaac/snowshu/adapters/source_adapters/snowflake_adapter.py#L74) to return the same as the UTILS_DB lookup. note that this includes meta for time travel databases that no longer exist, so some filtering is likely in order.

**Comment by BenjaminDavison** [comment]
> Ah yeah, this is an oversight assuming admin permissions. `UTIL_DB` is core snowflake but requires accountadmin to query, which is probably the wrong way to tackle this. The right answer is probably to migrate the databases query in the Snowflake adapter to use `SHOW DATABASES`. We can hit this pretty quick and get a release patch out.

Interestingly, when I run this in the Snowflake UI as an accountadmin. I still get this error: `SQL compilation error: Database 'UTIL_DB' does not exist or not authorized.`

**Comment by norton120** [comment]
That's weird. Out of curiosity what region is your SF instance in?

**Comment by BenjaminDavison** [comment]
eu-west-1

**Comment by norton120** [comment]
Including `DESC SCHEMA` and `DESC COLUMNS` here - the entire lookup needs to move away from information_schema. this will kill #4 as well

**Comment by norton120** [comment]
This _specific_ issue is fixed via 0.0.2 but migrating completely to SHOW in Snowflake is its own issue. #47
